export * from "./InicioScreen"
export * from "./NosotrosScreen"
export * from "./BeneficiosScreen"
export * from "./FuncionesScreen"
export * from "./TestimoniosScreen"
export * from "./PlanesScreen"
export * from "./ContactScreen"
