export * from "./InicioScreen"
export * from "./NosotrosScreen"
export * from "./BeneficiosScreen"
export * from "./ServiciosScreen"
export * from "./TestimoniosScreen"
export * from "./LastCtaScreen"
export * from "./ContactScreen"
export * from "./Footer"